---
- name: Install Supporting Packages
  sudo: yes
  apt: update_cache=yes pkg={{item}} state=present
  with_items:
    - nginx
    - uwsgi
    - python-dev
    - mysql-client
    - libmysqlclient-dev
    - uwsgi-plugin-python
    - python-pip
    - build-essential
    - python-setuptools
    - python-virtualenv
    - git
    - libjpeg-dev
    - libmemcached-dev
    - libpcre3-dev

- name: Add app user
  user: name={{ app_user }} state=present
  sudo: yes
  tags:
    - users

- name: Add app user authorized keys
  authorized_key: user={{app_user}} key="{{lookup('file', inventory_dir + '/keys/' + item.key)}}"
  sudo: yes
  with_items: admin_keys
  tags:
    - users

- name: Add install directory and virtualenv
  sudo: yes
  file: path={{ item }} owner={{ app_user }} group={{ app_user }} state=directory mode=0775
  with_items:
    - "{{samestrem.virtualenv}}"
    - "{{samestrem.install_dir}}"

- name: Add log dir
  file: path={{samestrem.logfile}} owner={{app_user}} group={{app_user}} state=touch mode=0777
  sudo: yes

- name: Add socket dir
  file: path="{{samestrem.socket_dir}}" owner="www-data" group="www-data" state=directory mode=0777
  sudo: yes

- name: Remove default vhost
  sudo: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  tags:
    - nginx
  notify:
    - Restart nginx

- name: Install uWSGI endpoint
  sudo: yes
  template: src=uwsgi.ini dest=/etc/uwsgi/apps-enabled/{{samestrem.app_name}}.ini owner=root
  notify:
    - Restart uWSGI

- name: Install nginx vhosts
  sudo: yes
  template: src=nginx.conf dest=/etc/nginx/sites-enabled/{{samestrem.app_name}}.conf owner=root
  tags:
    - nginx
  notify:
    - Restart nginx

- name: Install nginx key
  sudo: yes
  copy: src={{server_key}} dest=/etc/nginx/{{server_key}}
  when: server_key is defined
  tags:
    - nginx
  notify:
    - Restart nginx

- name: Install nginx cert
  sudo: yes
  copy: src={{server_cert}} dest=/etc/nginx/{{server_cert}}
  when: server_key is defined
  tags:
    - nginx
  notify:
    - Restart nginx

- name: Sync code up to web servers
  remote_user: "{{app_user}}"
  synchronize: delete=yes src={{samestrem.source_dir}} dest={{samestrem.install_dir}} rsync_opts=--exclude-from={{inventory_dir}}/samestrem-rsync-exclude
  when: is_vagrant is not defined or not is_vagrant
  notify:
    - Restart uWSGI
  tags:
    - deploy

- name: Push config.cfg
  sudo: yes
  template: src=config.yml dest={{samestrem.config_file}}
  notify:
    - Restart uWSGI
  tags:
    - deploy

- name: Set up virtualenv
  remote_user: "{{app_user}}"
  pip: virtualenv={{samestrem.virtualenv}} requirements={{samestrem.requirements_file}}
  tags:
    - virtualenv
  notify:
    - Restart uWSGI
